name: Laravel-Checklist

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    name: Laravel Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        touch storage/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: storage/database.sqlite
      run: vendor/bin/phpunit

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/development'
    steps:
    - uses: actions/checkout@v2
#     - name: Download build assets
#       uses: actions/download-artifact@v1
#       with:
#         name: assets
#         path: public
#     - name: Setup PHP
#       uses: shivammathur/setup-php@master
#       with:
#         php-version: 7.3
#         extension-csv: mbstring, bcmath
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup Deployer
      uses: atymic/deployer-php-action@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - name: Deploy to Prod
      env:
        DOT_ENV: ${{ secrets.DOT_ENV }}
      run: dep deploy development --tag=${{ env.GITHUB_REF }} -vvv
